### ISSUE TITLE
Investigate morph.io

### ISSUE THREAD

**Issue by patcon** [Changaco/legi.py#2]
Not that you need it to do what you're doing here, but in case you want to help build another interesting platform while working on your own effort :)

https://github.com/openaustralia/morph
https://morph.io/

It's a relaunch of what wikiscraper classic was -- open scrapers from github repos, which regularly spin up containers and scrape sites, making the results available via API.

But it's not quite at the place where scraperwiki was when it shut down. For instance, when you call the API, you need to pass manual sql queries, whereas wikiscraper offered an API that worked a little more as expected. But it's still a new project.

All the best @Changaco!

**Comment by Changaco** [comment]
Thanks patcon, all the best to you too. :wink:
